### ISSUE TITLE
Consider adding summary/description in the 'About' section, and a weblike to a crates.io page?

### ISSUE THREAD

**Issue by johnnyutahh** [HKalbasi/clap-repl#1]
Filling in "the About blank" below will help me remember what this project is about next time I'm "flipping through" all my projects/tools reference. I'd like to remember clap-repl, because it seems quite useful.

A reference to a crates.io page, if any, might help too. (Warning: I'm a Rust newbie, so I may not know what I'm talking about.)

<img width="1106" alt="macOS-Screenshot 2023-06-29 at 3 48 02 PM" src="https://github.com/HKalbasi/clap-repl/assets/8906609/3a01530e-a33e-4a94-ad17-4bddafa60589">

**Comment by hkalbasi** [comment]
Thanks for suggestion. Is it now good?

**Comment by johnnyutahh** [comment]
It now looks great, much appreciated. Closing this issue.
