### ISSUE TITLE
Feature Request: skip ctrl-c exit in read_command

### ISSUE THREAD

**Issue by BobAnkh** [HKalbasi/clap-repl#6]
`clap-repl` is a great tool. I would like to know if it's possible to make `ClapEditor` ignore the ctrl-c and ctrl-d signals, i.e., not to exit when these two signals are received, but to ignore the current input and continue to listen for new line input. For `reedline` or `rustyline`, I can handle such signals myself, but `clap-repl` directly exits when it receives these two signals, which prevents me from customizing the handling of these signals. 

I would like to know if `clap-repl` could possibly support configurations for whether to exit or provide a new version of `read_command` that does not exit? 

I'm fine if this is not possible in the project; then I will have to implement it myself.

**Comment by hkalbasi** [comment]
I made the `read_command` function more low level and also added a `repl` function which you can use in a loop if you just want to continue receiving commands (but make sure that you have a way to exit, otherwise you should kill your program with a signal or task manager).

I will publish a `v0.3` in the following days (I want to also change the constructor and use a builder) but you can use the git version meanwhile.

**Comment by BobAnkh** [comment]
> I made the `read_command` function more low level and also added a `repl` function which you can use in a loop if you just want to continue receiving commands (but make sure that you have a way to exit, otherwise you should kill your program with a signal or task manager).
> 
> I will publish a `v0.3` in the following days (I want to also change the constructor and use a builder) but you can use the git version meanwhile.

Thank you very much! Really appreciate your efforts!

**Comment by nixpulvis** [comment]
I'm playing with `ClapEditor::repl_async`, however I'm not sure if it's possible to define custom behavior for signals. I would like to make ctrl-c exit the program, but long term I may need for custom code in this case.

**Comment by hkalbasi** [comment]
Wouldn't inlining `repl_async` and using `read_command` suffice for your needs?
