### ISSUE TITLE
failed to resolve: could not find `dynamic` in `clap_complete`

### ISSUE THREAD

**Issue by carlocaione** [HKalbasi/clap-repl#8]
Using `clap-repl = "0.2.0"` when I compile a simple skeleton code I get:

```
❯ cargo run
   Compiling clap-repl v0.2.0
error[E0433]: failed to resolve: could not find `dynamic` in `clap_complete`
  --> /Users/carlo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap-repl-0.2.0/src/lib.rs:31:38
   |
31 |         let mut cmd = clap_complete::dynamic::shells::CompleteCommand::augment_subcommands(cmd);
   |                                      ^^^^^^^ could not find `dynamic` in `clap_complete`

error[E0433]: failed to resolve: could not find `dynamic` in `clap_complete`
  --> /Users/carlo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap-repl-0.2.0/src/lib.rs:42:45
   |
42 |         let Ok(candidates) = clap_complete::dynamic::complete(
   |                                             ^^^^^^^ could not find `dynamic` in `clap_complete`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `clap-repl` (lib) due to 2 previous errors
```

**Comment by hkalbasi** [comment]
It should be fixed in the main branch. Since the `unstable_dynamic` feature of the `clap_complete` is unstable, it can break in semver minor and patch versions. I have plans to make a `v0.3` soon, but you can use `clap-repl` as a git dependency or manually pin the clap-complete in your project to a good version for now.

**Comment by carlocaione** [comment]
git pinning `clap-repl` to the latest commit it works but I had also to manually add `clap` to my `Cargo.toml`. In general making a `v0.3` could be a good idea otherwise `v0.2` is currently broken as is.

**Comment by hkalbasi** [comment]
I made a `v0.3`. Please tell me if there were any more problems,
